export interface Cliente{
    id: number;
    sucursal_id: number;
    zona_id: number;
    agencia_id: number;
    num_cliente: number;
    num_cliente2: string;
    nombre: string;
    apellido_paterno: string;
    apellido_materno: string;
    fecha_nacimiento: Date;
    nombre_completo: string;
    telefono: string;
    curp: string;
    rfc: string;
    email: string;
    sexo: string;
    tipo_cliente: string;
    calle: string;
    colonia_id: number;
    cp: number;
    num_ext: string;
    num_int: string;
    cruzamientos: string;
    referencia: string;
    municipio: string;
    localidad: string;
    estado: string;
}